// SPDX-License-Identifier: MIT
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

export const PACKAGE_METADATA_START = "<!-- package-metadata:start -->";
export const PACKAGE_METADATA_END = "<!-- package-metadata:end -->";
export const PACKAGE_GRAPH_START = "<!-- package-dependency-graph:start -->";
export const PACKAGE_GRAPH_END = "<!-- package-dependency-graph:end -->";
export const PACKAGE_DIRECTORY_START = "<!-- package-directory:start -->";
export const PACKAGE_DIRECTORY_END = "<!-- package-directory:end -->";
export const PACKAGE_DIRECTORY_PAGE_FRONTMATTER = [
  "---",
  'title: "Packages"',
  'description: "Directory of every mono-agent v1 source package, its ownership tier, responsibility, and authoritative README."',
  "sidebar:",
  "  order: 1",
  "---",
].join("\n");
export const REQUIRED_PACKAGE_README_SECTIONS = Object.freeze([
  "Category",
  "Responsibility",
  "Install / Usage",
  "Architecture",
  "Public API",
  "Dependency Boundary",
  "What This Package Does Not Own",
  "Related Documentation",
  "Verification",
]);

const CATEGORY_ORDER = [
  "app",
  "operator-surface",
  "communication",
  "execution",
  "context",
  "observability",
  "core",
  "runtime",
  "evaluation",
];

export function packageTier(entry) {
  return entry.tier ?? "core";
}

export function renderPackageMetadata(entry) {
  return [
    PACKAGE_METADATA_START,
    "<!-- Generated by scripts/generate-package-docs.mjs. Do not edit by hand. -->",
    "",
    `Category: \`${entry.category}\``,
    `Tier: \`${packageTier(entry)}\``,
    `Catalog responsibility: ${entry.responsibility}`,
    "",
    PACKAGE_METADATA_END,
  ].join("\n");
}

export function updatePackageReadmeMetadata(readme, renderedMetadata) {
  const section = markdownSection(readme, "## Category");
  if (section === undefined) {
    throw new Error("README is missing its ## Category section.");
  }
  const existing = markedBlock(readme, PACKAGE_METADATA_START, PACKAGE_METADATA_END);
  if (existing !== undefined) {
    const blockStart = readme.indexOf(existing);
    if (blockStart < section.headingEnd || blockStart + existing.length > section.end) {
      throw new Error("Generated package metadata must be inside the real ## Category section.");
    }
    return readme.replace(existing, renderedMetadata);
  }

  const headingEnd = section.headingEnd;
  const body = readme.slice(headingEnd, section.end)
    .replace(/^\s*Category:\s*`[^`]+`\s*$/mu, "")
    .replace(/^\s*Tier:\s*`[^`]+`\s*$/mu, "")
    .replace(/^\s*Catalog responsibility:\s*.*$/mu, "")
    .replace(/^\n+/u, "")
    .replace(/\n+$/u, "");
  const replacement = `\n\n${renderedMetadata}${body.length > 0 ? `\n\n${body}` : ""}\n\n`;
  return `${readme.slice(0, headingEnd)}${replacement}${readme.slice(section.end).replace(/^\n+/u, "")}`;
}

export function collectPackageDocModel({ root, catalog }) {
  const byName = new Map(catalog.map((entry) => [entry.name, entry]));
  return catalog.map((entry) => {
    const packagePath = entry.path ?? `packages/${entry.dir}`;
    const manifestPath = join(root, packagePath, "package.json");
    if (!existsSync(manifestPath)) {
      throw new Error(`${packagePath}/package.json is missing.`);
    }
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    const dependencyNames = Object.keys({
      ...manifest.dependencies,
      ...manifest.optionalDependencies,
      ...manifest.peerDependencies,
    }).filter((name) => byName.has(name)).sort(compareText);
    return {
      ...entry,
      packagePath,
      manifest,
      tier: packageTier(entry),
      dependencyNames,
    };
  });
}

export function renderPackageDependencyGraph(model) {
  const coreCount = model.filter((entry) => entry.tier === "core").length;
  const pluginCount = model.filter((entry) => entry.tier === "plugin").length;
  const aliasCount = model.filter((entry) => entry.tier === "alias").length;
  const publishableCount = model.filter((entry) => entry.publishable === true).length;
  const lines = [
    PACKAGE_GRAPH_START,
    "<!-- Generated by scripts/generate-package-docs.mjs. Do not edit by hand. -->",
    "",
    `Current catalog: ${coreCount} core-tier packages, ${pluginCount} plugin-tier extras, and ${aliasCount} unscoped alias; all ${publishableCount} publishable entries release in lockstep.`,
    "",
    "**Diagram summary:** Solid arrows point from each package to the workspace packages it imports. Plugin loading, HTTP calls, and other runtime-only relationships are described after the diagram instead of being presented as package dependencies.",
    "",
    "```mermaid",
    "flowchart TB",
  ];

  for (const category of CATEGORY_ORDER) {
    const entries = model.filter((entry) => entry.category === category).sort(comparePackage);
    if (entries.length === 0) continue;
    lines.push(`  subgraph ${mermaidId(`category-${category}`)}["${category}"]`);
    for (const entry of entries) {
      const suffix = entry.tier === "plugin" ? "\\nplugin extra" : entry.tier === "alias" ? "\\nalias" : "";
      lines.push(`    ${mermaidId(entry.name)}["${entry.name}${suffix}"]`);
    }
    lines.push("  end", "");
  }

  for (const entry of [...model].sort(comparePackage)) {
    for (const dependencyName of entry.dependencyNames) {
      lines.push(`  ${mermaidId(entry.name)} --> ${mermaidId(dependencyName)}`);
    }
  }
  lines.push(
    "```",
    "",
    "**Text dependency summary:** Each row names a package and every workspace package it imports directly. `None` means the package has no direct workspace-package dependency.",
    "",
    "| Package | Direct workspace dependencies |",
    "| --- | --- |",
  );
  for (const entry of [...model].sort(compareCatalogPosition)) {
    const dependencies = entry.dependencyNames.length === 0
      ? "None"
      : entry.dependencyNames.map((name) => `\`${name}\``).join(", ");
    lines.push(`| \`${entry.name}\` | ${dependencies} |`);
  }
  lines.push("", PACKAGE_GRAPH_END);
  return lines.join("\n");
}

export function renderPackageDirectory(model, { website = false } = {}) {
  const lines = [
    PACKAGE_DIRECTORY_START,
    "<!-- Generated by scripts/generate-package-docs.mjs. Do not edit by hand. -->",
    "",
    "| Package | Tier / category | Responsibility | Links |",
    "| --- | --- | --- | --- |",
  ];
  for (const entry of [...model].sort(compareCatalogPosition)) {
    const readmeUrl = website
      ? `https://github.com/robertsreberski/mono-agent-next/blob/main/${entry.packagePath}/README.md`
      : `./${entry.packagePath}/README.md`;
    lines.push(
      `| \`${entry.name}\` | \`${entry.tier}\` / \`${entry.category}\` | ${escapeTable(entry.responsibility)} | [README for ${entry.name}](${readmeUrl}) |`,
    );
  }
  lines.push("", PACKAGE_DIRECTORY_END);
  return lines.join("\n");
}

export function updatePackageDirectoryPage(text, renderedDirectory) {
  const body = text.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n*/u, "");
  return [
    PACKAGE_DIRECTORY_PAGE_FRONTMATTER,
    "",
    updateMarkedBlock(
      body,
      PACKAGE_DIRECTORY_START,
      PACKAGE_DIRECTORY_END,
      renderedDirectory,
    ),
  ].join("\n");
}

export function updateMarkedBlock(text, startMarker, endMarker, rendered) {
  const existing = markedBlock(text, startMarker, endMarker);
  if (existing === undefined) {
    throw new Error(`Missing generated block ${startMarker}.`);
  }
  return text.replace(existing, rendered);
}

export function findPackageDocGenerationErrors({ root, catalog }) {
  const errors = [];
  let model;
  try {
    model = collectPackageDocModel({ root, catalog });
  } catch (error) {
    return [error instanceof Error ? error.message : String(error)];
  }

  for (const entry of model) {
    const readmePath = join(root, entry.packagePath, "README.md");
    if (!existsSync(readmePath)) continue;
    const readme = readFileSync(readmePath, "utf8");
    const actual = markedBlock(readme, PACKAGE_METADATA_START, PACKAGE_METADATA_END);
    const expected = renderPackageMetadata(entry);
    const categorySection = markdownSection(readme, "## Category");
    const blockStart = actual === undefined ? -1 : readme.indexOf(actual);
    const metadataIsInCategory = categorySection !== undefined
      && blockStart >= categorySection.headingEnd
      && blockStart + (actual?.length ?? 0) <= categorySection.end;
    if (actual !== expected || !metadataIsInCategory) {
      errors.push(`${entry.packagePath}/README.md package metadata has drifted; run pnpm run generate:package-docs.`);
    }
  }

  const packagesPath = join(root, "PACKAGES.md");
  if (existsSync(packagesPath)) {
    const packages = readFileSync(packagesPath, "utf8");
    if (markedBlock(packages, PACKAGE_GRAPH_START, PACKAGE_GRAPH_END) !== renderPackageDependencyGraph(model)) {
      errors.push("PACKAGES.md dependency graph has drifted; run pnpm run generate:package-docs.");
    }
    if (markedBlock(packages, PACKAGE_DIRECTORY_START, PACKAGE_DIRECTORY_END) !== renderPackageDirectory(model)) {
      errors.push("PACKAGES.md package directory has drifted; run pnpm run generate:package-docs.");
    }
  }

  const websiteDirectoryPath = join(root, "docs/reference/packages.md");
  if (!existsSync(websiteDirectoryPath)) {
    errors.push("docs/reference/packages.md is missing; run pnpm run generate:package-docs.");
  } else {
    const websiteDirectory = readFileSync(websiteDirectoryPath, "utf8");
    if (updatePackageDirectoryPage(
      websiteDirectory,
      renderPackageDirectory(model, { website: true }),
    ) !== websiteDirectory) {
      errors.push("docs/reference/packages.md package directory has drifted; run pnpm run generate:package-docs.");
    }
  }
  return errors;
}

export function findPackageReadmeStructureErrors({ root, catalog }) {
  const errors = [];
  for (const entry of catalog) {
    const packagePath = entry.path ?? `packages/${entry.dir}`;
    const readmePath = join(root, packagePath, "README.md");
    if (!existsSync(readmePath)) continue;
    const readme = readFileSync(readmePath, "utf8");
    const headings = markdownHeadings(readme);
    const h1s = headings.filter((heading) => heading.level === 1);
    if (h1s.length !== 1 || h1s[0].text !== entry.name) {
      errors.push(`${packagePath}/README.md must have exactly one H1 named \`${entry.name}\`.`);
    }

    const h2s = headings.filter((heading) => heading.level === 2);
    if (JSON.stringify(h2s.map((heading) => heading.text)) !== JSON.stringify(REQUIRED_PACKAGE_README_SECTIONS)) {
      errors.push(`${packagePath}/README.md H2 sections must appear exactly in the standard package order.`);
      continue;
    }

    const introduction = readme.slice(h1s[0]?.end ?? 0, h2s[0].start);
    if (!hasReadableContent(introduction)) {
      errors.push(`${packagePath}/README.md needs a consumer-first introduction before \`## Category\`.`);
    }

    const sections = new Map(h2s.map((heading, index) => [
      heading.text,
      readme.slice(heading.end, h2s[index + 1]?.start ?? readme.length),
    ]));
    for (const sectionName of REQUIRED_PACKAGE_README_SECTIONS) {
      if (!hasReadableContent(sections.get(sectionName) ?? "")) {
        errors.push(`${packagePath}/README.md section \`## ${sectionName}\` must not be empty.`);
      }
    }

    const install = sections.get("Install / Usage") ?? "";
    if (!install.includes(entry.name)) {
      errors.push(`${packagePath}/README.md \`## Install / Usage\` must show the published package name \`${entry.name}\`.`);
    }

    const architecture = sections.get("Architecture") ?? "";
    const architectureHeadings = markdownHeadings(architecture)
      .filter((heading) => heading.level === 3)
      .map((heading) => heading.text);
    for (const required of ["Data flow", "Package structure"]) {
      if (!architectureHeadings.includes(required)) {
        errors.push(`${packagePath}/README.md \`## Architecture\` must include \`### ${required}\`.`);
      }
    }

    const publicApi = sections.get("Public API") ?? "";
    const startHere = markdownHeadings(publicApi).find((heading) => heading.level === 3 && heading.text === "Start here");
    if (startHere === undefined) {
      errors.push(`${packagePath}/README.md \`## Public API\` must begin with a curated \`### Start here\` map.`);
    } else {
      const inventoryStart = publicApi.indexOf("<!-- public-api-inventory:start -->");
      if (inventoryStart !== -1 && startHere.start > inventoryStart) {
        errors.push(`${packagePath}/README.md \`### Start here\` must precede the generated public API inventory.`);
      }
      const startHereEnd = markdownHeadings(publicApi)
        .find((heading) => heading.start > startHere.start && heading.level <= 3)?.start ?? publicApi.length;
      if (!hasReadableContent(publicApi.slice(startHere.end, startHereEnd))) {
        errors.push(`${packagePath}/README.md \`### Start here\` must explain the package's main entry points.`);
      }
    }

    const related = sections.get("Related Documentation") ?? "";
    if (!/\[[^\]]+\]\([^)]+\)/u.test(related)) {
      errors.push(`${packagePath}/README.md \`## Related Documentation\` must link to canonical documentation.`);
    }
  }
  return errors;
}

function markedBlock(text, startMarker, endMarker) {
  const start = text.indexOf(startMarker);
  if (start === -1) return undefined;
  const end = text.indexOf(endMarker, start + startMarker.length);
  if (end === -1) return undefined;
  if (text.indexOf(startMarker, start + startMarker.length) !== -1
    || text.indexOf(endMarker, end + endMarker.length) !== -1) return undefined;
  return text.slice(start, end + endMarker.length);
}

function markdownHeadings(text) {
  const headings = [];
  const lines = text.split(/\r?\n/u);
  let offset = 0;
  let activeFence;
  for (const line of lines) {
    if (activeFence !== undefined) {
      if (new RegExp(`^\\s*${activeFence.marker}{${activeFence.length},}\\s*$`, "u").test(line)) activeFence = undefined;
      offset += line.length + 1;
      continue;
    }
    const fence = /^\s*(`{3,}|~{3,})/u.exec(line);
    if (fence !== null) {
      activeFence = { marker: fence[1][0], length: fence[1].length };
      offset += line.length + 1;
      continue;
    }
    const match = /^\s{0,3}(#{1,6})\s+(.+?)\s*#*\s*$/u.exec(line);
    if (match !== null) {
      headings.push({
        level: match[1].length,
        text: match[2].replace(/[`*_]/gu, "").trim(),
        start: offset,
        end: offset + line.length,
      });
    }
    offset += line.length + 1;
  }
  return headings;
}

function hasReadableContent(value) {
  return value
    .replace(/<!--[\s\S]*?-->/gu, "")
    .trim().length > 0;
}

function markdownSection(text, heading) {
  const expected = /^##\s+(.+)$/u.exec(heading)?.[1];
  if (expected === undefined) return undefined;
  const headings = markdownHeadings(text).filter((candidate) => candidate.level === 2);
  const matches = headings.filter((candidate) => candidate.text === expected);
  if (matches.length !== 1) return undefined;
  const match = matches[0];
  const next = headings.find((candidate) => candidate.start > match.start);
  return {
    start: match.start,
    headingEnd: match.end,
    end: next?.start ?? text.length,
  };
}

function mermaidId(value) {
  return `P_${value.replace(/[^A-Za-z0-9]+/gu, "_").replace(/^_+|_+$/gu, "")}`;
}

function escapeTable(value) {
  return String(value).replace(/\|/gu, "\\|").replace(/\s+/gu, " ").trim();
}

function compareCatalogPosition(left, right) {
  const categoryDifference = CATEGORY_ORDER.indexOf(left.category) - CATEGORY_ORDER.indexOf(right.category);
  return categoryDifference || comparePackage(left, right);
}

function comparePackage(left, right) {
  return compareText(left.name, right.name);
}

function compareText(left, right) {
  return left.localeCompare(right, "en");
}
